### ISSUE TITLE
[My Profile] New corresponding page of icons display error " Page not found"

### ISSUE THREAD

**Issue by at-trangnguyen3** [queenscity/internship-2019-winter-Web01#5]
**Test Environment**
- Date time: 20/02/2020 08:35
- Device: IMAC/ Safari 12.1
- Build: [STG] AT-Portal v1.9.4-beta

**Pre- conditions**

My Profile page is opened

**Step to perform**
1. Click each icon

**Actual Result**

 **At step 1**: 

- Skype corresponding page of user display error "Safari can't open the specified address."
- Chatwork corresponding page of user display error " Page not found"
- Github corresponding page of user display error " Page not found"
- Redmine corresponding page of user display error " Page not found"

**Expected Result**

 **At step 1**: Move to new corresponding page

![Screen Shot 2020-02-20 at 8 57 42 AM](https://user-images.githubusercontent.com/59002065/74893793-c5c36f80-53bf-11ea-8d9a-42336e7aedf2.png)
![Screen Shot 2020-02-20 at 8 58 01 AM](https://user-images.githubusercontent.com/59002065/74893796-c825c980-53bf-11ea-9f2c-6b3ed6699b15.png)
![Screen Shot 2020-02-20 at 8 58 32 AM](https://user-images.githubusercontent.com/59002065/74893799-c956f680-53bf-11ea-9eb5-216da5c4529e.png)
![Screen Shot 2020-02-20 at 8 58 48 AM](https://user-images.githubusercontent.com/59002065/74893800-c9ef8d00-53bf-11ea-8f15-5a693168d7a8.png)

**Account test**  stg.vy.vo2@asiantech.vn/Abc123@@

**Comment by at-vyvth** [comment]
- Remine => sai chính tả
- Issue này không phải là bug. Ra error vì chưa login account vào.
