### ISSUE TITLE
[My Profile] Submit button is NOT enable when input 7 character into [New Password] textbox.

### ISSUE THREAD

**Issue by at-cuongtruong** [queenscity/internship-2019-winter-Web01#8]
**Enviroment**

- STG Environment
- Build version : AT-Portal v1.9.4-beta
- Device : iMac (macOS version 10.14.4)
- Browser: Chrome (version: 80.0.3987.116 (64 bit))

**Pre-Condition**

- Open [Change Password area]

**Step to perform**

1. input value into [New Password] textbox is "Cuong1!".  
2. Input valid value into remaining textboxs.
3. Check status.
4. Click on [submit] button. 

**Actual Result**

At step 3: Submit button is disable.

**Expected Result**

At step 3: Submit button is enable and can click. 
At step 4: Show error pop-up [Must contain at least 8 characters (including a digit, an upper case character and a symbol).] is red color

**Account test**

stg.huong.le@asiantech.vn/Abc123@@

**Evidence**

![Ảnh chụp Màn hình 2020-02-20 lúc 9 24 23 SA](https://user-images.githubusercontent.com/59002145/74895397-189f2600-53c4-11ea-9e11-dc0f4250cad9.png)

**Comment by at-huongle** [comment]
Theo spec minimum là 8 character, em nhập có 7 thì chưa thoả điều kiện để enable submit button. Vì vậy đây không phải là bug. 
Trước khi log bug thì nhớ check lại thật kĩ spec với case mình đang test để make sure đây là bug hay không nha

**Comment by at-cuongtruong** [comment]
@at-huongle DONE.
